#!/bin/sh /etc/rc.common

START=15
STOP=1

PID_FILE="/tmp/pcat2-display-mini.pid"

start() {
	start-stop-daemon -bm -p ${PID_FILE} -S /usr/bin/photonicat2_mini_display
}

stop() {
	start-stop-daemon -p ${PID_FILE} -K /usr/bin/photonicat2_mini_display
	sleep 1
}

restart() {
	stop
	sleep 5
	start
}

shutdown() {
	stop
}
