#!/bin/sh
is_first_boot=`uci -q get zz_config.@status[0].first_boot`
if test $is_first_boot -gt 0; then

uci set luci.main.lang='zh_cn'
uci set luci.main.mediaurlbase='/luci-static/argon'
uci set attendedsysupgrade.client.login_check_for_upgrades='0'
uci del firewall.@defaults[0].flow_offloading_hw

uci set qmodem.main.start_delay='15'
uci del qmodem.main.enable_pcie_scan
uci set qmodem.main.enable_usb_scan='1'
uci set qmodem.wwan=modem-slot
uci set qmodem.wwan.type='usb'
uci set qmodem.wwan.slot='2-1.1'
uci set qmodem.wwan.alias='wwan'

uci commit
/etc/init.d/network reload

sed -i '/qmodem/d' /etc/apk/repositories.d/distfeeds.list

uci set fstab.@global[0].anon_mount='0'

STOR_DEV_FIRST="/dev/mmcblk1p1"
STOR_DEV_FIRST_MOUNT="/mnt/mmcblk1p1"
STOR_DEV_SECOND="/dev/mmcblk0p3"
STOR_DEV_SECOND_MOUNT="/mnt/mmcblk0p3"

if [ -b "$STOR_DEV_SECOND" ]; then
    uci add fstab mount
    uci set fstab.@mount[-1].enabled='1'
    uci set fstab.@mount[-1].device="$STOR_DEV_SECOND"
    uci set fstab.@mount[-1].target="$STOR_DEV_SECOND_MOUNT"
    STOR_DEV_TO_MOUNT="$STOR_DEV_SECOND"
    STOR_MOUNT_POINT="$STOR_DEV_SECOND_MOUNT"
fi
if [ -b "$STOR_DEV_FIRST" ]; then
    uci add fstab mount
    uci set fstab.@mount[-1].enabled='1'
    uci set fstab.@mount[-1].device="$STOR_DEV_FIRST"
    uci set fstab.@mount[-1].target="$STOR_DEV_FIRST_MOUNT"
    STOR_DEV_TO_MOUNT="$STOR_DEV_FIRST"
    STOR_MOUNT_POINT="$STOR_DEV_FIRST_MOUNT"
fi

uci commit fstab
/sbin/block mount
/bin/sleep 1s

if [ -n "$STOR_DEV_TO_MOUNT" ]; then
    if [ ! -d "$STOR_MOUNT_POINT/bandix" ]; then
        mkdir -p "$STOR_MOUNT_POINT/bandix"
    fi
    uci set bandix.general.data_dir="$STOR_MOUNT_POINT/bandix"
    uci commit bandix
else
    echo "persistent dev not found" >> /tmp/zz-init.log
fi

uci del bandix.traffic.traffic_neighbor_flush_interval
uci set bandix.traffic.enabled='1'
uci set bandix.traffic.traffic_enable_storage='1'
uci set bandix.connections.enabled='1'
uci set bandix.dns.enabled='1'
uci set bandix.dns.dns_enable_storage='1'
uci set bandix.traffic.traffic_flush_interval='300'
uci set bandix.dns.dns_flush_interval='300'
uci set bandix.traffic.traffic_realtime_window='1800'
uci commit bandix
/etc/init.d/bandix restart

/etc/init.d/pcat2-display-mini enable
/etc/init.d/pcat2-display-mini start

uci -q set zz_config.@status[0].first_boot=0
uci commit zz_config

fi

uci set argon.@global[0].mode='dark'
uci set argon.@global[0].online_wallpaper='none'
uci set argon.@global[0].transparency_dark='0.3'
uci commit argon

exit 0
