#!/bin/sh
is_first_boot=`uci -q get zz_config.@status[0].first_boot`
if test $is_first_boot -gt 0; then
# uci del dhcp.lan.ra_slaac
# uci del network.lan.ipaddr
# uci add_list network.lan.ipaddr='10.0.0.1/24'
# uci add_list network.lan.ip6class='2_1_2v6'

uci set luci.main.lang='zh_cn'
uci set luci.main.mediaurlbase='/luci-static/argon'
# uci set luci.main.mediaurlbase='/luci-static/alpha'
uci set attendedsysupgrade.client.login_check_for_upgrades='0'
uci del firewall.@defaults[0].flow_offloading_hw

uci set qmodem.main.start_delay='15'
uci del qmodem.main.enable_pcie_scan
uci set qmodem.main.enable_usb_scan='1'
uci set qmodem.wwan=modem-slot
uci set qmodem.wwan.type='usb'
uci set qmodem.wwan.slot='2-1.1'
uci set qmodem.wwan.alias='wwan'
# uci set qmodem.main.at_tool='1'
# uci commit qmodem

uci commit
/etc/init.d/network reload

sed -i '/qmodem/d' /etc/apk/repositories.d/distfeeds.list

uci set bandix.traffic.enabled='1'
uci set bandix.traffic.traffic_persist_history='1'
uci set bandix.traffic.traffic_flush_interval_seconds='300'
uci set bandix.connections.enabled='1'
uci set bandix.dns.enabled='1'
uci commit bandix
/etc/init.d/bandix restart

uci -q set zz_config.@status[0].first_boot=0
uci commit zz_config

/etc/init.d/pcat2-display-mini enable
/etc/init.d/pcat2-display-mini start

fi

uci set argon.@global[0].mode='dark'
uci set argon.@global[0].online_wallpaper='none'
uci set argon.@global[0].transparency_dark='0.3'
uci commit argon
uci set alpha.@navbar[2].name='bandix'
uci set alpha.@navbar[2].enable='Enable'
uci set alpha.@navbar[2].icon='/www/luci-static/alpha/zz/icon/navbar/bandwidth.png'
uci set alpha.@navbar[2].address='/cgi-bin/luci/admin/network/bandix'
uci set alpha.@navbar[3].name='Modem'
uci set alpha.@navbar[3].icon='/www/luci-static/alpha/gaya/icon/navbar/modem.png'
uci set alpha.@navbar[3].address='/cgi-bin/luci/admin/modem/qmodem'
uci set alpha.@navbar[4].name='Wireless'
uci set alpha.@navbar[4].icon='/www/luci-static/alpha/zz/icon/navbar/wifi.png'
uci set alpha.@navbar[4].address='/cgi-bin/luci/admin/network/wireless'
uci commit alpha

exit 0
