# SPDX-License-Identifier: GPL-3.0-only
#
# Copyright (C) 2026 zzzz0317 <github-pcat2@zhangzhe.net>
#

include $(TOPDIR)/rules.mk

PKG_LICENSE:=GPL-2.0

LUCI_TITLE:=LuCI Photonicat 2 Power Status App
LUCI_DEPENDS:=+luci-base

PKG_MAINTAINER:=zzzz0317 <github-pcat2@zhangzhe.net>

PKG_VERSION:=1.0.0
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
